Repository almondiz/almondiz-server, pull requests merged in 2022-09, with the labels that each got.

#21 Feature/#16 Notification
  src/main/java/org/almondiz/almondiz/exception/ExceptionAdvice.java
  src/main/java/org/almondiz/almondiz/exception/exception/CNotificationNotFoundException.java
  src/main/java/org/almondiz/almondiz/exception/exception/CNotificationNotPermittedException.java
  src/main/java/org/almondiz/almondiz/notification/Notification.java
  src/main/java/org/almondiz/almondiz/notification/NotificationController.java
  src/main/java/org/almondiz/almondiz/notification/NotificationRepository.java
  src/main/java/org/almondiz/almondiz/notification/NotificationResponseDto.java
  src/main/java/org/almondiz/almondiz/notification/NotificationService.java
  src/main/java/org/almondiz/almondiz/notification/NotificationType.java
  src/main/java/org/almondiz/almondiz/user/UserService.java
Labels: feature 💻

#24 Feature/#15 Follow 구현
  src/main/java/org/almondiz/almondiz/common/TimeStamped.java
  src/main/java/org/almondiz/almondiz/exception/ExceptionAdvice.java
  src/main/java/org/almondiz/almondiz/exception/exception/CFollowExistedException.java
  src/main/java/org/almondiz/almondiz/exception/exception/CFollowNotFoundException.java
  src/main/java/org/almondiz/almondiz/exception/exception/CFollowNotPermittedException.java
  src/main/java/org/almondiz/almondiz/follow/Follow.java
  src/main/java/org/almondiz/almondiz/follow/FollowController.java
  src/main/java/org/almondiz/almondiz/follow/FollowRepository.java
  src/main/java/org/almondiz/almondiz/follow/FollowRequestDto.java
  src/main/java/org/almondiz/almondiz/follow/FollowService.java
  src/main/java/org/almondiz/almondiz/follow/FollowerResponseDto.java
  src/main/java/org/almondiz/almondiz/follow/FollowingResponseDto.java
  src/main/java/org/almondiz/almondiz/user/UserService.java
Labels: feature 💻

#28 [bugfix] #27 UserService 중복 메소드 수정
  src/main/java/org/almondiz/almondiz/user/UserService.java
Labels: bug :cry:, 리뷰중 :eyes:

#26 Feature/#17 글쓰기(Post) 구현
  src/main/java/org/almondiz/almondiz/category/entity/Category.java
  src/main/java/org/almondiz/almondiz/config/security/SecurityConfig.java
  src/main/java/org/almondiz/almondiz/exception/exception/PostFileNotFoundException.java
  src/main/java/org/almondiz/almondiz/exception/exception/PostNotFoundException.java
  src/main/java/org/almondiz/almondiz/exception/exception/StoreNotFoundException.java
  src/main/java/org/almondiz/almondiz/follow/FollowService.java
  src/main/java/org/almondiz/almondiz/nut/NutService.java
  src/main/java/org/almondiz/almondiz/post/PostController.java
  src/main/java/org/almondiz/almondiz/post/PostService.java
  src/main/java/org/almondiz/almondiz/post/dto/PostRequestDto.java
  src/main/java/org/almondiz/almondiz/post/dto/PostResponseDto.java
  src/main/java/org/almondiz/almondiz/post/entity/Post.java
  src/main/java/org/almondiz/almondiz/post/entity/PostRepository.java
  src/main/java/org/almondiz/almondiz/postFile/PostFileService.java
  src/main/java/org/almondiz/almondiz/postFile/entity/PostFile.java
  src/main/java/org/almondiz/almondiz/postFile/entity/PostFileRepository.java
  src/main/java/org/almondiz/almondiz/profileFile/ProfileFileService.java
  src/main/java/org/almondiz/almondiz/store/StoreService.java
  src/main/java/org/almondiz/almondiz/store/entity/Store.java
  src/main/java/org/almondiz/almondiz/store/entity/StoreRepository.java
  src/main/java/org/almondiz/almondiz/tag/TagService.java
  src/main/java/org/almondiz/almondiz/user/UserController.java
  src/main/java/org/almondiz/almondiz/user/UserService.java
  src/main/java/org/almondiz/almondiz/user/entity/User.java
Labels: done ✔️, feature 💻, reviewing :eyes:

#34 JWT 및 Security 적용하여 AuthService 생성 및 수정, 헤더 추가
  build.gradle
  src/main/java/org/almondiz/almondiz/comment/CommentController.java
  src/main/java/org/almondiz/almondiz/common/ValidStringUtils.java
  src/main/java/org/almondiz/almondiz/config/security/CAccessDeniedHandler.java
  src/main/java/org/almondiz/almondiz/config/security/CAuthenticationEntryPoint.java
  src/main/java/org/almondiz/almondiz/config/security/ExceptionController.java
  src/main/java/org/almondiz/almondiz/config/security/JwtAuthenticationFilter.java
  src/main/java/org/almondiz/almondiz/config/security/SecurityConfig.java
  src/main/java/org/almondiz/almondiz/exception/ExceptionAdvice.java
  src/main/java/org/almondiz/almondiz/exception/exception/CAccessDeniedException.java
  src/main/java/org/almondiz/almondiz/exception/exception/CAuthenticationEntryPointException.java
  src/main/java/org/almondiz/almondiz/exception/exception/CExpiredTokenException.java
  src/main/java/org/almondiz/almondiz/exception/exception/CNotValidEmailException.java
  src/main/java/org/almondiz/almondiz/exception/exception/CRefreshTokenException.java
  src/main/java/org/almondiz/almondiz/exception/exception/CTokenUserNotFoundException.java
  src/main/java/org/almondiz/almondiz/follow/FollowController.java
  src/main/java/org/almondiz/almondiz/notification/NotificationController.java
  src/main/java/org/almondiz/almondiz/post/PostController.java
  src/main/java/org/almondiz/almondiz/user/AuthService.java
  src/main/java/org/almondiz/almondiz/user/UserController.java
  src/main/java/org/almondiz/almondiz/user/UserService.java
  src/main/java/org/almondiz/almondiz/user/dto/UserLogInDto.java
  src/main/java/org/almondiz/almondiz/user/entity/Token.java
  src/main/java/org/almondiz/almondiz/user/entity/User.java
Labels: bugfix ✋, feature 💻, reviewing :eyes:

#37 [feature] #31 DB 서버 세팅
  src/main/resources/application.properties
Labels: setting :hammer:, help wanted :sos:, reviewing :eyes:

#44 [feature] #42 Store CRUD 로직 구현
  src/main/java/org/almondiz/almondiz/exception/ExceptionAdvice.java
  src/main/java/org/almondiz/almondiz/exception/exception/StoreExistedException.java
  src/main/java/org/almondiz/almondiz/store/StoreService.java
  src/main/java/org/almondiz/almondiz/store/entity/Store.java
  src/main/java/org/almondiz/almondiz/store/entity/StoreRepository.java
  src/main/java/org/almondiz/almondiz/store/entity/StoreRequestDto.java
  src/main/java/org/almondiz/almondiz/store/entity/StoreResponseDto.java
Labels: feature 💻, reviewing :eyes:

#52 [bugfix] #45 cors error
  src/main/java/org/almondiz/almondiz/config/security/CorsConfig.java
  src/main/java/org/almondiz/almondiz/config/security/SecurityConfig.java
Labels: bug :cry:, reviewing :eyes:

#48 Feature/#43 StoreScrap
  src/main/java/org/almondiz/almondiz/exception/ExceptionAdvice.java
  src/main/java/org/almondiz/almondiz/exception/exception/StoreScrapExistedException.java
  src/main/java/org/almondiz/almondiz/exception/exception/StoreScrapNotFoundException.java
  src/main/java/org/almondiz/almondiz/exception/exception/StoreScrapNotPermittedException.java
  src/main/java/org/almondiz/almondiz/nut/NutService.java
  src/main/java/org/almondiz/almondiz/post/PostService.java
  src/main/java/org/almondiz/almondiz/postFile/PostFileService.java
  src/main/java/org/almondiz/almondiz/profileFile/ProfileFileService.java
  src/main/java/org/almondiz/almondiz/store/StoreService.java
  src/main/java/org/almondiz/almondiz/storescrap/StoreScrap.java
  src/main/java/org/almondiz/almondiz/storescrap/StoreScrapController.java
  src/main/java/org/almondiz/almondiz/storescrap/StoreScrapRepository.java
  src/main/java/org/almondiz/almondiz/storescrap/StoreScrapResponseDto.java
  src/main/java/org/almondiz/almondiz/storescrap/StoreScrapService.java
  src/main/java/org/almondiz/almondiz/tag/TagService.java
  src/main/java/org/almondiz/almondiz/user/UserService.java
Labels: feature 💻, reviewing :eyes:

#54 [bugfix] #45 cors error
  src/main/java/org/almondiz/almondiz/config/security/CorsConfig.java
Labels: bug :cry:

#51 [feature] #49 post 디테일 페이지 api 구현
  src/main/java/org/almondiz/almondiz/comment/CommentService.java
  src/main/java/org/almondiz/almondiz/comment/dto/CommentResponseDto.java
  src/main/java/org/almondiz/almondiz/post/PostService.java
  src/main/java/org/almondiz/almondiz/post/dto/PostResponseDto.java
  src/main/java/org/almondiz/almondiz/post/entity/Post.java
  src/main/java/org/almondiz/almondiz/user/UserService.java
  src/main/java/org/almondiz/almondiz/user/dto/UserAsWriterResponseDto.java
  src/main/resources/application-cloud.properties
Labels: feature 💻, reviewing :eyes:

#53 Feature/#50 피드 API 구현
  src/main/java/org/almondiz/almondiz/comment/entity/CommentRepository.java
  src/main/java/org/almondiz/almondiz/post/PostController.java
  src/main/java/org/almondiz/almondiz/post/PostService.java
  src/main/java/org/almondiz/almondiz/post/dto/PostInFeedResponseDto.java
Labels: feature 💻, reviewing :eyes:

#56 [feature] #23 exception명 변경
  src/main/java/org/almondiz/almondiz/comment/CommentService.java
  src/main/java/org/almondiz/almondiz/common/ValidStringUtils.java
  src/main/java/org/almondiz/almondiz/config/security/ExceptionController.java
  src/main/java/org/almondiz/almondiz/exception/ExceptionAdvice.java
  src/main/java/org/almondiz/almondiz/exception/exception/AccessDeniedException.java
  src/main/java/org/almondiz/almondiz/exception/exception/AccountExistedException.java
  src/main/java/org/almondiz/almondiz/exception/exception/AuthenticationEntryPointException.java
  src/main/java/org/almondiz/almondiz/exception/exception/CAccessDeniedException.java
  src/main/java/org/almondiz/almondiz/exception/exception/CAccountExistedException.java
  src/main/java/org/almondiz/almondiz/exception/exception/CAuthenticationEntryPointException.java
  src/main/java/org/almondiz/almondiz/exception/exception/CExpiredTokenException.java
  src/main/java/org/almondiz/almondiz/exception/exception/CFollowExistedException.java
  src/main/java/org/almondiz/almondiz/exception/exception/CFollowNotFoundException.java
  src/main/java/org/almondiz/almondiz/exception/exception/CFollowNotPermittedException.java
  src/main/java/org/almondiz/almondiz/exception/exception/CNotValidEmailException.java
  src/main/java/org/almondiz/almondiz/exception/exception/CNotificationNotFoundException.java
  src/main/java/org/almondiz/almondiz/exception/exception/CNotificationNotPermittedException.java
  src/main/java/org/almondiz/almondiz/exception/exception/CRefreshTokenException.java
  src/main/java/org/almondiz/almondiz/exception/exception/CTokenUserNotFoundException.java
  src/main/java/org/almondiz/almondiz/exception/exception/CUserNotFoundException.java
  src/main/java/org/almondiz/almondiz/exception/exception/ExpiredTokenException.java
  src/main/java/org/almondiz/almondiz/exception/exception/FollowExistedException.java
  src/main/java/org/almondiz/almondiz/exception/exception/FollowNotFoundException.java
  src/main/java/org/almondiz/almondiz/exception/exception/FollowNotPermittedException.java
  src/main/java/org/almondiz/almondiz/exception/exception/NotValidEmailException.java
  src/main/java/org/almondiz/almondiz/exception/exception/NotificationNotFoundException.java
  src/main/java/org/almondiz/almondiz/exception/exception/NotificationNotPermittedException.java
  src/main/java/org/almondiz/almondiz/exception/exception/RefreshTokenException.java
  src/main/java/org/almondiz/almondiz/exception/exception/TokenUserNotFoundException.java
  src/main/java/org/almondiz/almondiz/exception/exception/UserNotFoundException.java
  src/main/java/org/almondiz/almondiz/follow/Follow.java
  src/main/java/org/almondiz/almondiz/follow/FollowService.java
  src/main/java/org/almondiz/almondiz/notification/Notification.java
  src/main/java/org/almondiz/almondiz/notification/NotificationService.java
  src/main/java/org/almondiz/almondiz/post/PostService.java
  src/main/java/org/almondiz/almondiz/storescrap/StoreScrapService.java
  src/main/java/org/almondiz/almondiz/user/AuthService.java
  src/main/java/org/almondiz/almondiz/user/UserService.java
  src/main/java/org/almondiz/almondiz/user/entity/User.java
Labels: bugfix ✋, reviewing :eyes:
